# Ce fichier est configuré pour la formation
formation_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: FORMATION_ROLE
      database: FORMATION_DB
      warehouse: FORMATION_WH
      schema: "GOLD_{{ env_var('SNOWFLAKE_USER') }}"
      threads: 4