version: 2

sources:
  - name: SNOWFLAKE_DBT
    description: "Sources de données du système Snowflake DBT"
    database: SNOWFLAKE_DBT
    schema: PUBLIC
    tables:
      - name: BRANDS
        description: "Table des marques"
      - name: CATEGORIES
        description: "Table des catégories de produits"
      - name: CUSTOMERS
        description: "Table des clients"
      - name: ORDER_ITEMS
        description: "Table des articles de commande"
      - name: PRODUCTS
        description: "Table des produits"
        columns:
          - name: product_id
            description: "Clé primaire des produits"
            data_tests:
              - unique
              - not_null
      - name: STORES
        description: "Table des magasins"
